blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/vowstar/lefdef-viewer/discussions
    about: Please ask and answer questions here.
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
