name: Documentation Issue
description: Report an issue with the documentation
title: "[Docs]: "
labels: ["documentation"]
assignees:
  - vowstar
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our documentation!
  - type: dropdown
    id: type
    attributes:
      label: Type of documentation issue
      description: What type of documentation issue is this?
      options:
        - Typo/Grammar
        - Missing information
        - Outdated information
        - Unclear explanation
        - Code example issue
        - Other (please describe below)
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Documentation location
      description: Where is the documentation you're reporting an issue with?
      placeholder: "e.g., README.md, website page URL, code comments in file X"
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What's the issue?
      description: Please describe the issue with the documentation
      placeholder: A clear and concise description of what's wrong or missing.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement
      description: If you have a specific suggestion to improve the documentation, please share it.
      placeholder: Your suggestion for how to fix or improve the documentation.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the documentation issue here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vowstar/lefdef-viewer/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
